version: '3.3'

services:
  frontend:
    # env_file:
    #   - frontend/.env
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    ports:
      - "0.0.0.0:80:80"
    expose:
      - 80

  backend:
    # env_file:
    #   - backend/.env
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    ports:
      - "0.0.0.0:8000:8000"
    expose:
      - 8000